### ISSUE TITLE
Adding A axis to Mpg on screen

### ISSUE THREAD

**Issue by alkabal** [wolfmanjm/kivy-smoothie-host#17]
Hi

What do you think about adding the A axis ?

I have try but something is wrong regarding to the integrated Dro from the Mpg widget.

```
        ToggleButton:
            text: 'Z'
            group: 'axis'
            size_hint_y: None
            height: 40
            on_state: if self.state == 'down': root.selected_axis= self.text
        ToggleButton:
            text: 'A'
            group: 'axis'
            size_hint_y: None
            height: 40
            on_state: if self.state == 'down': root.selected_axis= self.text
        ToggleButton:
            id: Fo
            text: 'Fo'
            group: 'axis'
            size_hint_y: None
            height: 40
            on_state: if self.state == 'down': root.selected_axis= self.text
```
These work partialy i think something is wrong regarding  

root.selected_axis= self.text or root.index_changed or root.selected_index

But i don't understand.

Br
